spring:
  #profiles: cloud
  application:
    name: currency-exchange-service

server:
  port: ${CCY_EXCHANGE_SERVER_PORT:9090}

eureka: 
  instance: 
    hostName: ${NAMING_SERVER_HOST:localhost}
    ipAddress: ${NAMING_SERVER_HOST_IP:127.0.0.1}
    leaseExpirationDurationInSeconds: 30
    leaseRenewalIntervalInSeconds: 30
    nonSecurePort: ${NAMING_SERVER_PORT:8761}
    nonSecurePortEnabled: true
    preferIpAddress: true    
    
  client:
    eurekaServerDNSName: ${NAMING_SERVER_HOST:localhost}
    eurekaServerPort: ${NAMING_SERVER_PORT:8761}
    eurekaServerURLContext: eureka
    fetchRegistry: true
    registerWithEureka: true
    registryFetchIntervalSeconds: 30
    useDnsForFetchingServiceUrls: false
    serviceUrl:
      defaultZone: http://${NAMING_SERVER_HOST:localhost}:${NAMING_SERVER_PORT:8761}/eureka

feign:
    client:
        config:
            default:
              connectTimeout: 50000
              loggerLevel: basic
              readTimeout: 50000
logging:
    level:
        com:
            currencyexchange:
              docker: DEBUG
            netflix:
              loadbalancer:
                DynamicServerListLoadBalancer: DEBUG
              
ribbon:
    eagerLoad:
        enabled: true
    eureka:
        enabled: true